name: Run Performance Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g lighthouse

    - name: Run Lighthouse
      run: lighthouse http://localhost --output json --output html --output-path ./lighthouse-results.html
